export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Nav from "./components/Nav";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "lightgrey", }}>
        <Nav></Nav>
        {children}
        <footer>
          <h3>Footer is here</h3>
          <p>&copy;Robert Davis</p>
        </footer>
      </body>
    </html>
  );
}
