export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", display: "flex", justifyContent: "space-evenly" }}>
          <a href="/about">Profile</a>
          <a href="/pictures">Pictures</a>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
