export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue" }}>
          <a href="/about">Profile</a>
          <br />
          <a href="/pictures">API Page</a>
        </header>
        {children}

        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
